service: ecommerce-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  ordersFunction:
    handler: services/orders/handler_orders.handler
    events:
      - http:
          path: orders
          method: get

      - http:
          path: orders/{id}
          method: get 

  productsFunction:
    handler: services/products/handler_products.handler
    events:
      - http:
          path: products
          method: get

  customersFunction:
    handler: services/customers/handler_customers.handler
    events:
      - http:
          path: customers
          method: post

  authFunction:
    handler: services/auth/handler_auth.handler
    events:
      - http:
          path: auth
          method: post
  
  shippingFunction:
    handler: services/shipping/shipping_service.handler
    events:
      - http:
          path: shipping
          method: post

  productSuggestorFunction:
    handler: services/product_suggestor/handler_product_suggestor.handler
    events:
      - http:
          path: product_suggestor
          method: post