service: ecommerce-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

functions:
  ordersFunction:
    handler: services/orders/handler_orders.handler
    events:
      - http:
          path: orders
          method: get

      - http:
          path: orders/{id}
          method: get 

  productsFunction:
    handler: services/products/handler_products.handler
    events:
      - http:
          path: products
          method: get

  customersFunction:
    handler: services/customers/handler_customers.handler
    events:
      - http:
          path: customers
          method: post

  authFunction:
    handler: services/auth/handler_auth.handler
    events:
      - http:
          path: auth
          method: post
  
  shippingFunction:
    handler: services/shipping/shipping_service.handler
    events:
      - http:
          path: shipping
          method: post

  productSuggestorFunction:
    handler: services/product_suggestor/handler_product_suggestor.handler
    events:
      - http:
          path: product_suggestor
          method: post

  cartAddItemFunction:
    handler: services/cart/handler_cart_add_item.handler
    events:
      - http:
          path: cart/add_item
          method: post

  cartDeleteItemFunction:
    handler: services/cart/handler_cart_remove_item.handler
    events:
      - http:
          path: cart
          method: delete
      - http:
          path: cart/remove_item/{id}
          method: delete 

  cartFunction:
    handler: services/cart/handler_cart.handler
    events:
      - http:
          path: cart
          method: get
  
  paymentFunction:
    handler: services/cart/handler_end_payment.handler
    events:
      - http:
          path: checkout
          method: post

  configFunction:
    handler: services/configurations/handler_configurations.handler
    events:
      - http:
          path: configurations
          method: post

  getconfigFunction:
    handler: services/configurations/handler_get_configurations.handler
    events:
      - http:
          path: configurations
          method: get
