name: Deploy Microservices to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [orders, products]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install dependencies and zip
      working-directory: ${{ matrix.service }}
      run: |
        pip install -r requirements.txt -t package/
        cp app.py package/
        cd package
        zip -r ../${{ matrix.service }}.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ matrix.service }-service \
          --zip-file fileb://${{ matrix.service }}.zip \
          --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
